# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: TF
google_analytics: TF
title: TF

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Time Forest

description: Stylish Jekyll Theme
author:
  name: Bogyu Park
  email: roroii1285@gmail.com
  github: https://github.com/bgparkloop/
  #twitter: dbtek
  #pinterest: asd123
  linkedin: https://www.linkedin.com/in/bogyu-park-219185140
  bio: Study, Thought, Idea
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
